### ISSUE TITLE
ValueError(f"Unexpected type of activity: {activity}")

### ISSUE THREAD

**Issue by leeprevost** [bankroll-py/bankroll#106]
I get this error when attempting to run bankroll (even simple --help) after install in a fresh conda virtual environment (python 3.6).

$ bankroll --help
Traceback (most recent call last):
  File "c:\users\lee\anaconda3\envs\foliolyze\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\lee\anaconda3\envs\foliolyze\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\lee\Anaconda3\envs\foliolyze\Scripts\bankroll.exe\__main__.py", line 5, in <module>
  File "c:\users\lee\anaconda3\envs\foliolyze\lib\site-packages\bankroll\interface\__init__.py", line 1, in <module>
    from bankroll.analysis import *
  File "c:\users\lee\anaconda3\envs\foliolyze\lib\site-packages\bankroll\analysis\__init__.py", line 1, in <module>
    from .analysis import (
  File "c:\users\lee\anaconda3\envs\foliolyze\lib\site-packages\bankroll\analysis\analysis.py", line 88
    raise ValueError(f"Unexpected type of activity: {activity}")

**Comment by jspahrsummers** [comment]
I'm afraid I don't see how that call stack is possible (bankroll doesn't generally have module-level code, which is what seems to be implicated here).

Can you please include the error message after string interpolation, in case that sheds any light on the issue?
